steps:
  - task: UseDotNet@2
    displayName: Use .NET Core SDK 3.1.101
    inputs:
      packageType: sdk
      version: 3.1.101

  - script: $(Build.Repository.LocalPath)/Scripts/Mac/NukeBuildOutputs.sh
    displayName: Delete previous build outputs
    continueOnError: true

  - script: Scripts/Mac/BuildScalarForMac.sh $(configuration) $(majorAndMinorVersion).$(revision)
    displayName: Build Scalar ($(configuration))

  - script: Scripts/Mac/RunUnitTests.sh $(configuration) $(Common.TestResultsDirectory)
    displayName: Run unit tests ($(configuration))

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      searchFolder: $(Common.TestResultsDirectory)
      testRunTitle: Mac $(configuration) Unit Tests
      publishRunAttachments: true
    condition: succeededOrFailed()
